[YouTube-Extended]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "BashisPower/Backup"
integrations-source = "YT-Advanced/noway"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Add splash animation' 'Disable landscape mode' 'Enable debug logging' 'Enable song search' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide player button background' 'Hide voice search button' 'MaterialYou' 'Shorts outline button'"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
version = "19.05.36"
