[YouTube-Extended]
app-name = "YouTube"
patches-source = "YT-Advanced/revanced-patches"
integrations-source = "YT-Advanced/testintes"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
